### ISSUE TITLE
Toggle bool 

### ISSUE THREAD

**Issue by HalfDragonLucy** [Vili1/Among-us-external-noclip#1]
Using a toggle and putting the keys on WASD instead of 4 different keys sound better.

**Comment by Vili1** [comment]
> Using a toggle and putting the keys on WASD instead of 4 different keys sound better.

will do thanks for the feedback

**Comment by HalfDragonLucy** [comment]
W- GetAsyncKeyState(0x57)
A- GetAsyncKeyState(0x41)
S- GetAsyncKeyState(0x53)
D- GetAsyncKeyState(0x44)

**Comment by Vili1** [comment]
@HalfDragonLucy 
take a look now :v
